title: Worlorn
description: The long-standing Dungeons & Dragons world by Mark Gadziko
remote_theme: pages-themes/midnight@v0.2.0
plugins: 
- jekyll-remote-theme
navigation:
- personalities
- places
- things
- events
- groups
- vocabulary
