title: The World of Worlorn
description: A long-standing Dungeons & Dragons world by Mark Gadziko
theme: jekyll-theme-yat
remote_theme: "jeffreytse/jekyll-theme-yat"
plugins:
- jekyll-remote-theme
header_pages:
- README.md
