title: The World of Worlorn
description: A long-standing Dungeons & Dragons world by Mark Gadziko
remote_theme: "jeffreytse/jekyll-theme-yat"
night_mode: "on"
plugins:
- jekyll-remote-theme
header_pages:
- README.md
